using System.Net.Http;
using System.Threading.Tasks;

namespace TelegaBot.BotStuff
{
    public class Timetable
    {
        public static string Get(string uri)
        {
            using var siteClient = new HttpClient();
            string result = siteClient
                .GetAsync(uri).Result.Content
                .ReadAsStringAsync().Result;

            return result
                .Replace("// nika_data.js;  description: schedule in JSON format\r\n" +
                         "// this file automatically generated by Nika-Soft(c) products\r\n \r\n" +
                         "var NIKA=\r\n", "")
                .Trim()
                .Replace(";", "");
        }
    }
}